### ISSUE TITLE
Typescript still not working

### ISSUE THREAD

**Issue by davidmoshal** [HcySunYang/vuese#32]
**Describe the bug**
Typescript still not working

**To Reproduce**
Using just the parser, I ran the following:
```js
const { parser } = require('@vuese/parser')

// Read vue file content
const source = `
<template>
  <div>
    <button @click="clicked">click</button>
    <br>
    {{x}}
  </div>
</template>

<script lang="ts">
  import { Component, Prop, Vue } from 'vue-property-decorator'

  @Component
  export default class ModulesDemo extends Vue {

    @Prop() x :string

    clicked() {
      this.x = new Date().toString()
    }
  }
</script>

<style scoped>

</style>

  
`
// Parse and get the result using the parser function
try {
  console.log(source)
  const parserRes = parser(source)
  console.log(parserRes)
} catch(e) {
  console.error(e)
}

```
**Expected behavior**
Expected to see something in parserRes object.
Instead parserRes was empty:
```js
{ componentDesc: { default: [] } }
```

**Screenshots**
not applicable

**Which version do you use:**
1.4.7

**Additional information**
none

**Comment by HcySunYang** [comment]
Hi, `@Prop()` decorator requires parameters:
```ts
@Prop(....) x :string
```

In addition, the version you are using is 1.x? Your code uses `@vuese/parser`, which should be the 2.x version.

**Comment by davidmoshal** [comment]
@HcySunYang couple of comments:

1) `@vuese/parser` was 2.x

2) adding parameters to decorators does work, even with with vuese 1.4.7 (which I believe uses vuese/parser version 2.x), ie: the same parser.

However: 

Using `  import {  Prop } from 'vue-property-decorator` allows you to use the @Prop decoration without any parameters.

Is there any reason why you require parameters on the Prop and other decorators?

**Comment by HcySunYang** [comment]
@davidmoshal  Ok, this will be improved.

**Comment by davidmoshal** [comment]
thanks `@Prop a: string` seems like the correct Typescript idiom, not `@Prop(String) a` 

It would be great to be able to parse SFC components even more broadly.

For example:

a) ability to get a list of the imports referenced by an SFC.

b) ability to get a list of the dependent components.

Thanks

**Comment by HcySunYang** [comment]
I have added your feature request to the [roadmap](https://github.com/vuese/roadmap) and many people have told me that they want those features.

**Comment by davidmoshal** [comment]
@HcySunYang  thank you.

**Comment by sobolevn** [comment]
Hi, how is that going? Looking forward to add support of `vuese` to https://github.com/wemake-services/wemake-vue-template/issues/926 but this issue blocks me. 🙂

**Comment by HcySunYang** [comment]
@sobolevn 
Resolved, use the latest version:
 - @vuese/cli@2.2.1
 - @vuese/markdown-render@2.2.1
 - @vuese/parser@2.1.1

**Comment by sobolevn** [comment]
@HcySunYang still does not work for my setup. 

Here's the reproduction: https://github.com/wemake-services/wemake-vue-template/pull/1038

**Comment by HcySunYang** [comment]
Can you provide a minimum reproduce it? Or tell me the steps to reproduce [wemake-services/wemake-vue-template#1038](https://github.com/wemake-services/wemake-vue-template/pull/1038), perhaps you can open a new issue.
Thanks.

**Comment by sobolevn** [comment]
@HcySunYang here are the steps:

1. `git clone https://github.com/wemake-services/wemake-vue-template.git`
2. `git checkout feature-typescript`
3. `cd wemake-vue-template/template`
4. replace `{{ name }}` to `name` in `package.json`
5. `npm install`
6. `npm install -D @vuese/cli`
7. `./node_module/.bin/vuese gen`

**Comment by HcySunYang** [comment]
@sobolevn I follow the steps and can work correctly, as shown below:
![image](https://user-images.githubusercontent.com/14146560/54866566-56f52500-4db0-11e9-9718-4827ae3d17eb.png)
